{{- if not .Values.kibana.existingSecret }}
{{- if or .Values.kibana.endpoint .Values.kibana.apiKey .Values.kibana.username .Values.kibana.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tf-work.fullname" . }}-kibana
  labels:
    {{- include "tf-work.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.kibana.endpoint }}
  KIBANA_ENDPOINT: {{ . | quote }}
  {{- end }}
  {{- with .Values.kibana.apiKey }}
  KIBANA_API_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.kibana.username }}
  KIBANA_USERNAME: {{ . | quote }}
  {{- end }}
  {{- with .Values.kibana.password }}
  KIBANA_PASSWORD: {{ . | quote }}
  {{- end }}
{{- end }}
{{- end }}
