apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "tf-work.fullname" . }}
  labels:
    {{- include "tf-work.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "tf-work.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tf-work.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tf-work.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.kibana.existingSecret .Values.kibana.endpoint .Values.kibana.apiKey .Values.kibana.username .Values.kibana.password }}
          envFrom:
            - secretRef:
                name: {{ .Values.kibana.existingSecret | default (printf "%s-kibana" (include "tf-work.fullname" .)) }}
          {{- end }}
          env:
            - name: TF_VAR_kibana_insecure
              value: {{ .Values.kibana.insecure | toString | quote }}
            - name: KIBANA_INSECURE
              value: {{ .Values.kibana.insecure | toString | quote }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
